services:
  self-hosted_runner:
    build: .
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
      - ORG_NAME=${ORG_NAME}
      - REPO_URL=${REPO_URL}
    restart: unless-stopped
    command: sh -c "./config.sh --url ${REPO_URL} --token ${RUNNER_TOKEN} --name ${RUNNER_NAME} --labels ${RUNNER_LABELS} --unattended && ./run.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          cpus: "0.2"
          memory: 128M
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - telops_network

networks:
  telops_network:
    driver: bridge